/* Kilograms */
// Plate Weights
export const SET_KGS_25_PLATE_WEIGHT = 'SET_KGS_25_PLATE_WEIGHT';
export const SET_KGS_20_PLATE_WEIGHT = 'SET_KGS_20_PLATE_WEIGHT';
export const SET_KGS_15_PLATE_WEIGHT = 'SET_KGS_15_PLATE_WEIGHT';
export const SET_KGS_10_PLATE_WEIGHT = 'SET_KGS_10_PLATE_WEIGHT';
// Change Weights
export const SET_KGS_5_CHANGE_WEIGHT = 'SET_KGS_5_CHANGE_WEIGHT';
export const SET_KGS_2_5_CHANGE_WEIGHT = 'SET_KGS_2_5_CHANGE_WEIGHT';
export const SET_KGS_2_0_CHANGE_WEIGHT = 'SET_KGS_2_0_CHANGE_WEIGHT';
export const SET_KGS_1_5_CHANGE_WEIGHT = 'SET_KGS_1_5_CHANGE_WEIGHT';
export const SET_KGS_1_0_CHANGE_WEIGHT = 'SET_KGS_1_0_CHANGE_WEIGHT';
export const SET_KGS_0_5_CHANGE_WEIGHT = 'SET_KGS_0_5_CHANGE_WEIGHT';

/* Pounds */
// Plate Weights
export const SET_LBS_45_PLATE_WEIGHT = 'SET_LBS_45_PLATE_WEIGHT';
export const SET_LBS_35_PLATE_WEIGHT = 'SET_LBS_35_PLATE_WEIGHT';
export const SET_LBS_25_PLATE_WEIGHT = 'SET_LBS_25_PLATE_WEIGHT';
export const SET_LBS_10_PLATE_WEIGHT = 'SET_LBS_10_PLATE_WEIGHT';
// Change Weights
export const SET_LBS_5_CHANGE_WEIGHT = 'SET_LBS_5_CHANGE_WEIGHT';
export const SET_LBS_2_5_CHANGE_WEIGHT = 'SET_LBS_2_5_CHANGE_WEIGHT';
